services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--configfile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/routes.yml:/traefik/routes.yml:ro
      - ./traefik/certs:/certs:ro
    networks:
      - web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  nginx:
    image: dstixx05/nginx-app:latest
    container_name: nginx
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    security_opt:
      - no-new-privileges:true

networks:
  web:
    driver: bridge
