http:
  routers:
    nginx:
      rule: "Host(`127.0.0.2`)"
      service: nginx-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - security-headers

  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        customResponseHeaders:
          X-Powered-By: ""
          Server: ""

  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: "http://nginx:80"
